virtualenv:
	env\Scripts\activate

runserver:
	python .\manage.py runserver

makemigrations:
	python.exe .\manage.py makemigrations

migrate:
	python.exe .\manage.py migrate
superuser:
	python.exe .\manage.py createsuperuser
conversation:
	python.exe ./manage.py startapp conversation

.PHONY: virtualenv, runserver, makemigrations, migrate, superuser